meta_product_name: "Homie"
meta_title: "Homie - Homemaking Made Easy"
meta_description: "Homie is the place to be to organise your lists in your life, perfect for home, personal and work lists for yourself or to share with others.
When you are running low enter it into the app and it will remind you when you need it."
meta_image: "cover.png" # should exist in `app/assets/images/`
